services:
  - type: web
    name: opentok-pwa
    env: static
    buildCommand: npm install && npm run build:pwa
    staticPublishPath: ./dist
    packageManager: npm
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /sw.js
        name: Cache-Control
        value: no-cache
      - path: /manifest.json
        name: Cache-Control
        value: no-cache
      - path: /icons/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*
        name: Service-Worker-Allowed
        value: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        fromDatabase:
          name: opentok-db
          property: connectionString
      - key: VITE_SUPABASE_ANON_KEY
        fromDatabase:
          name: opentok-db
          property: anonKey
      - key: VITE_VAPID_PUBLIC_KEY
        generateValue: true
